// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhobckraqksdsxkwbqjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJob2Jja3JhcWtzZHN4a3dicWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzM5MTksImV4cCI6MjA3MDQwOTkxOX0.dTEWCm6C6Qo5v1U1Qz8w312s1lSF8RTJxUkP-ydgSKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});